;Istraziti video modu 320x200 u asembleru. Napraviti screen saver po uzoru na jedan stariji screen saver-e Windows-a 95 (https://www.youtube.com/watch?v=MKqrLGFoK9E&ab_channel=ronjamesscaresme). Umesto 3D screen saver-a odraditi njegovu 2D varijantu, sa linijama umesto "cevima". Uraditi ovo u grafickom rezimu rada (u video modu 320x200).
 
 
;Od korisnika se ocekuje samo da pritisne run, buduci da se program loop-uje, ocekuje se da korisnik prekine emulator na stop kada "izvrti" sve sto ima!
;Predlazem pokretanje programa jednom, a zatim citanje dokumentacije nakon toga. 



;                                                  Ideja iza i pojasnjenje uradjenog zadatka
;=================================================================================================================================================================; 
;Napravljeni su sabloni za 8 smerova, zamisliti sledece kretanje vrednosti cx i/ili dx po koordinatnom sistemu:

 ; x | y ;
 ;---|---;
 ; + | / ;
 ; - | / ;
 ; / | + ;
 ; / | - ;
 ; + | + ;
 ; - | - ;
 ; - | + ;
 ; + | - ;
 
;Zamisao je da se koriste svaka od tih 8 procedura (uz izmene vrednosti) kako bi se dobio izgled inspirisan screensaver-om sa snimka.

;Legenda procedura:
;
;DN - desnoN, LN - levoN, GON - goreN, DON - doleN, GDN - gore_desnoN, GLN - gore_levoN, DDN - dole_desnoN, DLN - dole_levoN
;
;N - redni broj petlje, npr. petljaD3 je 3. "desno" petlja koja se pojavljuje po redu u zadatku 



; Primer procedure za crtanje zelene linije duzine 30 piksela kretanjem pozitivno po x osi (ka desno):
;
;mov al, 10   <- Zelena boja
;mov si, 0 
;petljaD1:
;inc cx       <- Uvecavanjem cx registra linija ce se iscrtavati po pozitivnoj x osi (dakle ka desno)
;inc si
;int 10h
;cmp si,k     <- Poredimo si, koji je na pocetku 0, s predefinisanom konstantom k (30) i toliko piksela crtamo ka datom smeru...
;               ... promenom registra si ili k menjamo koliko "dugacko" ce nam se linija prostirati 
;JNE petljaD1  

;Zamisao je da se iscrta slika screenaver-a koristeci gore napomenute metode i zatim da se ocisti ekran nakon cega se pravi delay...
; ... kao kad bismo koristili screenaver u pravom zivotu i pomerili misa ili pritisnuli tipku na tastaturi pa screenaver nestane
;To postizemo ciscenjem ekrana i delayom(u pravom zivotu screenaver se ne prikazuje odmah nakon sto pomerimo misa).

; Nakon tog delaya krece da se crta drugi screenaver nakon cijeg crtanja se pojavljuje ciscenje i delay ponovo, i opet crta onaj prvi i tako...
; ... obezbedjujemo da nikad nemamo 2 iste iscrtane slike u nizu 

;"ciscenje" ekrana se postize stvaranjem novog [LOC:875], a ne zapravo ciscenjem ekrana tako sto bi se popunio space karakterima... to bi predugo trajalo 
;... u emulatoru (primer je makro "clrScreen"  s vezbi) 

;Celine su odvojene komentarima i predstavljaju jedan "crtez" na ekranu
;Nove celine na ekranu se crtaju tako sto se promene x,y koordinate piksela i zatim pozivaju definisane procedure sa izmenjenim vrednostima
;"Docrtavanje" celina se vrsi tako sto se x,y koordinate postave na koordinate koje su se koristile za crtanje tog crteza


 
;Ideja za doradu projekta jeste osposobljavanje pracenja unosa sa tastature tako da se ocisti ekran i dogodi delay cim se pritisne...
; ... bilo koja tipka sa tastature(ili jedna odredjena) u bilo kom trenutku crtanja slike 
;Takodje, ideja za doradu bi bilo pojednostavljenje samog projekta, pametnija izrada "crtanja" slike, potencijalno bez previse procedura.
;(Ugrubo prebrojano ukoliko je dobro indeksirano: petljaD: 15 | petljaDL: 15 | petljaGD: 10 | petljaDD: 5 | petljaL:10 | petljaGL:7 | petljaGO:11 | petljaDO:8)

;=================================================================================================================================================================;
jmp start

k dw 30  ;konstanta od 30 piskela za poredjenje sa si registrom
x dw 100 ;pozicija piksela za kolonu
y dw 100 ;pozicija piksela za red 


start:
mov ah, 00  ; postavljanje 320x200
mov al, 13h ; mode 13h  
int 10h     ; video memorija

mov cx, x   ;kolona
mov dx, y   ;red
mov ah, 0ch ;stavljanje piksela 
 




;------------------------------------------;
;               Celina 1                   ;
;------------------------------------------; 
mov cx,255                                 ;
mov dx,50                                  ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaD1:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,k                                   ;
                                           ;
JNE petljaD1                               ;
                                           ;
mov cx,255                                 ;
mov dx,50                                  ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO1:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,5                                   ;
JNE petljaGO1                              ;
                                           ;
                                           ;
mov al, 90                                 ;
mov si, 0                                  ;
petljaGD1:                                 ;
inc cx                                     ;
inc cx                                     ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,8                                   ;
JNE petljaGD1                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO2:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,5                                   ;
JNE petljaGO2                              ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL1:                                 ;
dec cx                                     ;
dec cx                                     ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,8                                   ;
JNE petljaDL1                              ;
                                           ;
;------------------------------------------;
;               Celina 1                   ;
;------------------------------------------; 



;------------------------------------------;
;               Celina 2                   ;
;------------------------------------------;
                                           ;
                                           ;
mov cx,240                                 ;
mov dx,70                                  ;
mov al, 25                                 ;
mov si, 0                                  ;
petljaDO1:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,15                                  ;
JNE petljaDO1                              ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGL1:                                 ;
dec cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaGL1                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO3:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,25                                  ;
JNE petljaGO3                              ;
                                           ;
;------------------------------------------;
;               Celina 2                   ;
;------------------------------------------;




;------------------------------------------; 
;               Celina 3                   ;
;------------------------------------------;
                                           ;
mov cx,100                                 ;
mov dx,70                                  ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaDO2:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,7                                   ;
JNE petljaDO2                              ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaGL2:                                 ;
                                           ;
dec dx                                     ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,11                                  ;
JNE petljaGL2                              ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO4:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaGO4                              ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL1:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaL1                               ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaDO3:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,25                                  ;
JNE petljaDO3                              ;
                                           ;
mov al, 5                                  ;
mov si, 0                                  ;
petljaD2:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaD2                               ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO5:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaGO5                              ;
;------------------------------------------; 
;               Celina 3                   ;
;------------------------------------------;


;------------------------------------------; 
;          Celina 2 - Nastavak             ;
;------------------------------------------;
mov cx, 240                                ;
mov dx, 70                                 ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL7:                                 ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,13                                  ;
JNE petljaDL7                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaDO6:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ;
JNE petljaDO6                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGL4:                                 ;
dec cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaGL4                              ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaD6:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,3                                   ;
JNE petljaD6                               ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGL5:                                 ;
dec cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaGL5                              ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO10:                                ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ; 
JNE petljaGO10                             ;
                                           ;
mov al, 90                                 ;
mov si, 0                                  ;
petljaGD:                                  ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ;
JNE petljaGD                               ;
                                           ;
                                           ;                                          
mov al, 10                                 ;
mov si, 0                                  ;
petljaDO7:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaDO7                              ;
                                           ;
                                           ;
;------------------------------------------;   
;               Celina 4                   ;
;------------------------------------------;
                                           ;
mov cx, 100                                ;
mov dx, 105                                ;
mov al, 12                                 ;
mov si, 0                                  ;
petljaDO4:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,14                                  ;
JNE petljaDO4                              ;
                                           ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL2:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaL2                               ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaDO5:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,3                                   ;
JNE petljaDO5                              ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL2:                                 ;
dec cx                                     ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,9                                   ;
JNE petljaDL2                              ;
                                           ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL3:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ;
JNE petljaL3                               ;
                                           ;
                                           ;
mov al, 90                                 ;
mov si, 0                                  ;
petljaGD2:                                 ;
inc cx                                     ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,9                                   ;
JNE petljaGD2                              ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO6:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaGO6                              ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL3:                                 ;
dec cx                                     ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,9                                   ;
JNE petljaDL3                              ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaD3:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ;
JNE petljaD3                               ;
                                           ;
                                           ;
mov al, 90                                 ;
mov si, 0                                  ;
petljaGD3:                                 ;
inc cx                                     ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,5                                   ;
JNE petljaGD3                              ;
                                           ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL4:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,8                                   ;
JNE petljaL4                               ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGD4:                                 ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,5                                   ;
JNE petljaGD4                              ;
                                           ;
                                           ;
mov al, 60                                 ;
mov si, 0                                  ;
petljaD4:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaD4                               ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL4:                                 ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaDL4                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO7:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,15                                  ;
JNE petljaGO7                              ;
                                           ;
;------------------------------------------;   
;               Celina 4                   ;
;------------------------------------------;


;------------------------------------------;   
;            Celina 1 - Nastavak           ;        
;------------------------------------------;
mov cx,253                                 ;
mov dx,41                                  ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO:                                  ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,5                                   ;
JNE petljaGO                               ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGL:                                  ;
dec cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,12                                  ;
JNE petljaGL                               ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL:                                   ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,18                                  ;
JNE petljaL                                ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL:                                  ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,6                                   ;
JNE petljaDL                               ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGL6:                                 ;
dec cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,3                                   ;
JNE petljaGL6                              ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL6:                                 ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,12                                  ;
JNE petljaDL6                              ;
                                           ;
                                           ;
mov al, 12                                 ;
mov si, 0                                  ;
petljaDD1:                                 ;
inc cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaDD1                              ;
;------------------------------------------;   
;            Celina 1 - Nastavak           ;        
;------------------------------------------;



;------------------------------------------;
;               Celina 5                   ;
;------------------------------------------;
mov cx, 300                                ;
mov dx, 130                                ;
mov al, 60                                 ;
mov si, 0                                  ;
petljaD5:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,17                                  ;
JNE petljaD5                               ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL5:                                 ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ;
JNE petljaDL5                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO8:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,5                                   ; 
JNE petljaGO8                              ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaGL3:                                 ;                                           
dec dx                                     ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,11                                  ;
JNE petljaGL3                              ;
                                           ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL5:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,11                                  ;
JNE petljaL5                               ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO9:                                 ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,9                                   ; 
JNE petljaGO9                              ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL8:                                 ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,12                                  ;
JNE petljaDL8                              ;
                                           ;
                                           ;
mov cx, 300                                ;
mov dx, 130                                ;
mov al, 90                                 ;
mov si, 0                                  ;
petljaGD5:                                 ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,k                                   ;
JNE petljaGD5                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaDO8:                                 ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,22                                  ;
JNE petljaDO8                              ;
                                           ;
                                           ;
mov al, 70                                 ;
mov si, 0                                  ;
petljaD7:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaD7                               ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL9:                                 ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,35                                  ;
JNE petljaDL9                              ;
                                           ;
                                           ;
mov al, 60                                 ;
mov si, 0                                  ;
petljaD8:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,17                                  ;
JNE petljaD8                               ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL10:                                ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ;
JNE petljaDL10                             ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGO11:                                ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,5                                   ; 
JNE petljaGO11                             ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGL7:                                 ;                                           
dec dx                                     ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,11                                  ;
JNE petljaGL7                              ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL11:                                ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,26                                  ;
JNE petljaDL11                             ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL6:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,45                                  ;
JNE petljaL6                               ;
                                           ;
;------------------------------------------;
;               Celina 5                   ;
;------------------------------------------;


;------------------------------------------;
;          Celina 3 - Nastavak             ;
;------------------------------------------;
                                           ;
mov cx,100                                 ;
mov dx,70                                  ;
mov al, 12                                 ;
mov si, 0                                  ;
petljaDD2:                                 ;
inc cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,12                                  ;
JNE petljaDD2                              ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaD9:                                  ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,20                                  ;
JNE petljaD9                               ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL12:                                ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,12                                  ;
JNE petljaDL12                             ;
                                           ;
                                           ;
mov al, 110                                ;
mov si, 0                                  ;
petljaDD3:                                 ;
inc cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,16                                  ;
JNE petljaDD3                              ;
;------------------------------------------;
;          Celina 3 - Nastavak             ;
;------------------------------------------;                                           
                                           
                                           
                                           
;------------------------------------------;
;        Delay i ciscenje ekrana 1         ;
;------------------------------------------;                                           
mov ah,00                                  ;
mov al,13h                                 ;
int 10h                                    ;
                                           ;
mov ax, 0                                  ;
mov dx, 378                                ;
out dx, ax                                 ;
mov ax, 1                                  ;
                                           ;
mov cx, 1ah                                ;
start1st:                                  ;
mov ax, 1                                  ;
left:                                      ;
out dx, ax                                 ;
mov bx, 2                                  ;
mul bx                                     ;
cmp ax, 80h                                ;
jl left                                    ;
dec cx                                     ;
cmp cx,0                                   ;
jg start1st                                ;
;------------------------------------------;
;        Delay i ciscenje ekrana 1         ;
;------------------------------------------;                                           
                                           ;
                                           ;
jmp start2                                 ;
                                           ;
start2:                                    ;
mov ah, 00  ; "drugi" skrinsaver           ;
mov al, 13h                                ;
int 10h                                    ;
;------------------------------------------;
;               Celina 6                   ;
;------------------------------------------;
mov cx, 285                                ;
mov dx, y                                  ;
mov ah, 0ch                                ;--<!Obavezno opet koristiti, puca u suprotnom.... bude eh mode koji nije podrzan za graficku memoriju!>
mov al, 14                                 ;
mov si, 0                                  ;
petljaL7:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,55                                  ;
JNE petljaL7                               ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL13:                                ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaDL13                             ;
                                           ;
                                           ;
mov al, 14                                 ;
mov si, 0                                  ;
petljaL8:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaL8                               ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGD6:                                 ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,3                                   ;
JNE petljaGD6                              ;
                                           ;
                                           ;
                                           ;
mov al, 90                                 ;
mov si, 0                                  ;
petljaL9:                                  ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,25                                  ;
JNE petljaL9                               ;
                                           ;
                                           ;
mov al, 40                                 ;
mov si, 0                                  ;
petljaDL14:                                ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,k                                   ;
JNE petljaDL14                             ;
                                           ;
                                           ;
mov al, 90                                 ;
mov si, 0                                  ;
petljaL10:                                 ;
dec cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,10                                  ;
JNE petljaL10                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGD7:                                 ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,k                                   ;
JNE petljaGD7                              ;
                                           ;
;------------------------------------------;
;               Celina 6                   ;
;------------------------------------------;


;------------------------------------------;
;               Celina 7                   ;
;------------------------------------------;
mov cx, 55                                 ;
mov dx, 75                                 ;
mov al, 66                                 ;
mov si, 0                                  ;
petljaD10:                                 ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,55                                  ;
JNE petljaD10                              ;
                                           ;
                                           ;
mov al, 12                                 ;
mov si, 0                                  ;
petljaDD4:                                 ;
inc cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaDD4                              ;
                                           ;
                                           ;
mov al, 66                                 ;
mov si, 0                                  ;
petljaD11:                                 ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaD11                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGD8:                                 ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaGD8                              ;
                                           ;
                                           ;
mov al, 66                                 ;
mov si, 0                                  ;
petljaD12:                                 ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaD12                              ;
                                           ;
                                           ;
mov al, 12                                 ;
mov si, 0                                  ;
petljaDD5:                                 ;
inc cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaDD5                              ;
                                           ;
                                           ;
mov al, 66                                 ;
mov si, 0                                  ;
petljaD13:                                 ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaD13                              ;
                                           ;
                                           ;
mov al, 10                                 ;
mov si, 0                                  ;
petljaGD9:                                 ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,4                                   ;
JNE petljaGD9                              ;
                                           ;
                                           ;
mov al, 66                                 ;
mov si, 0                                  ;
petljaD14:                                 ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,55                                  ;
JNE petljaD14                              ;
                                           ;
;------------------------------------------;
;               Celina 7                   ;
;------------------------------------------;



;------------------------------------------;
;               Celina 8                   ;
;------------------------------------------;                                           
mov cx, 55                                 ;
mov dx, 145                                ;
mov al, 100                                ;
mov si, 0                                  ;
petljaGD10:                                ;
inc cx                                     ;
inc cx                                     ;
dec dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,k                                   ;
JNE petljaGD10                             ;
                                           ;
mov al, 88                                 ;
mov si, 0                                  ;
petljaDL15:                                ;
dec cx                                     ;
inc dx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,k                                   ;
JNE petljaDL15                             ;
                                           ;
mov al, 66                                 ;
mov si, 0                                  ;
petljaD15:                                 ;
inc cx                                     ;
inc si                                     ;
int 10h                                    ;
cmp si,k                                   ;
JNE petljaD15                              ;
                                           ;
                                           ;
;------------------------------------------;
;        Delay i ciscenje ekrana 2         ;
;------------------------------------------;                                           
mov ah,00                                  ;
mov al,13h                                 ;
int 10h                                    ;
                                           ;
mov ax, 0                                  ;
mov dx, 378                                ;
out dx, ax                                 ;
mov ax, 1                                  ;
                                           ;
mov cx, 1ah                                ;
start2nd:                                  ;
mov ax, 1                                  ;
left2:                                     ;
out dx, ax                                 ;
mov bx, 2                                  ;
mul bx                                     ;
cmp ax, 80h                                ;
jl left2                                   ;
dec cx                                     ;
cmp cx,0                                   ;
jg start2nd                                ;
;------------------------------------------;
;        Delay i ciscenje ekrana 2         ;
;------------------------------------------;
jmp start 




 